version: '3.5'

services:
  db:
    image: postgres:15.2
    container_name: charity-postgres
    restart: always
    environment:
      POSTGRES_DB: charity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  keycloak:
    image: ghcr.io/cmps-department/charity-keycloak:1.0
    container_name: charity-keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"