version: '3.5'

services:
  db:
    image: postgres:15.2
    container_name: charity-postgres
    restart: always
    environment:
      POSTGRES_DB: charity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"