services:
  db:
    image: postgres:15.2
    container_name: charity-postgres
    restart: always
    environment:
      POSTGRES_DB: charity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: charity-keycloak
    restart: always
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev --import-realm
    ports:
      - "8080:8080"