spring:   # code for
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id # paste ID here
            client-secret: google-client-secret # paste Secret here